/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace Apache.Cassandra
{

  [Serializable]
  public partial class ColumnOrSuperColumn : TBase
  {
    private Column column;
    private SuperColumn super_column;

    public Column Column
    {
      get
      {
        return column;
      }
      set
      {
        __isset.column = true;
        this.column = value;
      }
    }

    public SuperColumn Super_column
    {
      get
      {
        return super_column;
      }
      set
      {
        __isset.super_column = true;
        this.super_column = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool column;
      public bool super_column;
    }

    public ColumnOrSuperColumn() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              this.column = new Column();
              this.column.Read(iprot);
              this.__isset.column = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Struct) {
              this.super_column = new SuperColumn();
              this.super_column.Read(iprot);
              this.__isset.super_column = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ColumnOrSuperColumn");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (this.column != null && __isset.column) {
        field.Name = "column";
        field.Type = TType.Struct;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        this.column.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (this.super_column != null && __isset.super_column) {
        field.Name = "super_column";
        field.Type = TType.Struct;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        this.super_column.Write(oprot);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("ColumnOrSuperColumn(");
      sb.Append("column: ");
      sb.Append(this.column== null ? "<null>" : this.column.ToString());
      sb.Append(",super_column: ");
      sb.Append(this.super_column== null ? "<null>" : this.super_column.ToString());
      sb.Append(")");
      return sb.ToString();
    }

  }

}
