/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

namespace Apache.Cassandra
{
  public enum AccessLevel
  {
    NONE = 0,
    READONLY = 16,
    READWRITE = 32,
    FULL = 64,
  }
}
