/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace Apache.Cassandra
{

  [Serializable]
  public partial class ColumnDef : TBase
  {
    private byte[] name;
    private string validation_class;
    private IndexType index_type;
    private string index_name;

    public byte[] Name
    {
      get
      {
        return name;
      }
      set
      {
        __isset.name = true;
        this.name = value;
      }
    }

    public string Validation_class
    {
      get
      {
        return validation_class;
      }
      set
      {
        __isset.validation_class = true;
        this.validation_class = value;
      }
    }

    public IndexType Index_type
    {
      get
      {
        return index_type;
      }
      set
      {
        __isset.index_type = true;
        this.index_type = value;
      }
    }

    public string Index_name
    {
      get
      {
        return index_name;
      }
      set
      {
        __isset.index_name = true;
        this.index_name = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool name;
      public bool validation_class;
      public bool index_type;
      public bool index_name;
    }

    public ColumnDef() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              this.name = iprot.ReadBinary();
              this.__isset.name = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              this.validation_class = iprot.ReadString();
              this.__isset.validation_class = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              this.index_type = (IndexType)iprot.ReadI32();
              this.__isset.index_type = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.String) {
              this.index_name = iprot.ReadString();
              this.__isset.index_name = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ColumnDef");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (this.name != null && __isset.name) {
        field.Name = "name";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(this.name);
        oprot.WriteFieldEnd();
      }
      if (this.validation_class != null && __isset.validation_class) {
        field.Name = "validation_class";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(this.validation_class);
        oprot.WriteFieldEnd();
      }
      if (__isset.index_type) {
        field.Name = "index_type";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)this.index_type);
        oprot.WriteFieldEnd();
      }
      if (this.index_name != null && __isset.index_name) {
        field.Name = "index_name";
        field.Type = TType.String;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(this.index_name);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("ColumnDef(");
      sb.Append("name: ");
      sb.Append(this.name);
      sb.Append(",validation_class: ");
      sb.Append(this.validation_class);
      sb.Append(",index_type: ");
      sb.Append(this.index_type);
      sb.Append(",index_name: ");
      sb.Append(this.index_name);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
