/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace Apache.Cassandra
{

  [Serializable]
  public partial class IndexClause : TBase
  {
    private List<IndexExpression> expressions;
    private byte[] start_key;
    private int count;

    public List<IndexExpression> Expressions
    {
      get
      {
        return expressions;
      }
      set
      {
        __isset.expressions = true;
        this.expressions = value;
      }
    }

    public byte[] Start_key
    {
      get
      {
        return start_key;
      }
      set
      {
        __isset.start_key = true;
        this.start_key = value;
      }
    }

    public int Count
    {
      get
      {
        return count;
      }
      set
      {
        __isset.count = true;
        this.count = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool expressions;
      public bool start_key;
      public bool count;
    }

    public IndexClause() {
      this.count = 100;
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                this.expressions = new List<IndexExpression>();
                TList _list8 = iprot.ReadListBegin();
                for( int _i9 = 0; _i9 < _list8.Count; ++_i9)
                {
                  IndexExpression _elem10 = new IndexExpression();
                  _elem10 = new IndexExpression();
                  _elem10.Read(iprot);
                  this.expressions.Add(_elem10);
                }
                iprot.ReadListEnd();
              }
              this.__isset.expressions = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              this.start_key = iprot.ReadBinary();
              this.__isset.start_key = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              this.count = iprot.ReadI32();
              this.__isset.count = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("IndexClause");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (this.expressions != null && __isset.expressions) {
        field.Name = "expressions";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, this.expressions.Count));
          foreach (IndexExpression _iter11 in this.expressions)
          {
            _iter11.Write(oprot);
            oprot.WriteListEnd();
          }
        }
        oprot.WriteFieldEnd();
      }
      if (this.start_key != null && __isset.start_key) {
        field.Name = "start_key";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(this.start_key);
        oprot.WriteFieldEnd();
      }
      if (__isset.count) {
        field.Name = "count";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(this.count);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("IndexClause(");
      sb.Append("expressions: ");
      sb.Append(this.expressions);
      sb.Append(",start_key: ");
      sb.Append(this.start_key);
      sb.Append(",count: ");
      sb.Append(this.count);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
