/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace Apache.Cassandra
{

  [Serializable]
  public partial class KeyRange : TBase
  {
    private string start_key;
    private string end_key;
    private string start_token;
    private string end_token;
    private int count;

    public string Start_key
    {
      get
      {
        return start_key;
      }
      set
      {
        __isset.start_key = true;
        this.start_key = value;
      }
    }

    public string End_key
    {
      get
      {
        return end_key;
      }
      set
      {
        __isset.end_key = true;
        this.end_key = value;
      }
    }

    public string Start_token
    {
      get
      {
        return start_token;
      }
      set
      {
        __isset.start_token = true;
        this.start_token = value;
      }
    }

    public string End_token
    {
      get
      {
        return end_token;
      }
      set
      {
        __isset.end_token = true;
        this.end_token = value;
      }
    }

    public int Count
    {
      get
      {
        return count;
      }
      set
      {
        __isset.count = true;
        this.count = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool start_key;
      public bool end_key;
      public bool start_token;
      public bool end_token;
      public bool count;
    }

    public KeyRange() {
      this.count = 100;
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              this.start_key = iprot.ReadString();
              this.__isset.start_key = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              this.end_key = iprot.ReadString();
              this.__isset.end_key = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.String) {
              this.start_token = iprot.ReadString();
              this.__isset.start_token = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.String) {
              this.end_token = iprot.ReadString();
              this.__isset.end_token = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.I32) {
              this.count = iprot.ReadI32();
              this.__isset.count = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("KeyRange");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (this.start_key != null && __isset.start_key) {
        field.Name = "start_key";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(this.start_key);
        oprot.WriteFieldEnd();
      }
      if (this.end_key != null && __isset.end_key) {
        field.Name = "end_key";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(this.end_key);
        oprot.WriteFieldEnd();
      }
      if (this.start_token != null && __isset.start_token) {
        field.Name = "start_token";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(this.start_token);
        oprot.WriteFieldEnd();
      }
      if (this.end_token != null && __isset.end_token) {
        field.Name = "end_token";
        field.Type = TType.String;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(this.end_token);
        oprot.WriteFieldEnd();
      }
      if (__isset.count) {
        field.Name = "count";
        field.Type = TType.I32;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(this.count);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("KeyRange(");
      sb.Append("start_key: ");
      sb.Append(this.start_key);
      sb.Append(",end_key: ");
      sb.Append(this.end_key);
      sb.Append(",start_token: ");
      sb.Append(this.start_token);
      sb.Append(",end_token: ");
      sb.Append(this.end_token);
      sb.Append(",count: ");
      sb.Append(this.count);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
