/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace Apache.Cassandra
{

  [Serializable]
  public partial class KeySlice : TBase
  {
    private string key;
    private List<ColumnOrSuperColumn> columns;

    public string Key
    {
      get
      {
        return key;
      }
      set
      {
        __isset.key = true;
        this.key = value;
      }
    }

    public List<ColumnOrSuperColumn> Columns
    {
      get
      {
        return columns;
      }
      set
      {
        __isset.columns = true;
        this.columns = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool key;
      public bool columns;
    }

    public KeySlice() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              this.key = iprot.ReadString();
              this.__isset.key = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                this.columns = new List<ColumnOrSuperColumn>();
                TList _list8 = iprot.ReadListBegin();
                for( int _i9 = 0; _i9 < _list8.Count; ++_i9)
                {
                  ColumnOrSuperColumn _elem10 = new ColumnOrSuperColumn();
                  _elem10 = new ColumnOrSuperColumn();
                  _elem10.Read(iprot);
                  this.columns.Add(_elem10);
                }
                iprot.ReadListEnd();
              }
              this.__isset.columns = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("KeySlice");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (this.key != null && __isset.key) {
        field.Name = "key";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(this.key);
        oprot.WriteFieldEnd();
      }
      if (this.columns != null && __isset.columns) {
        field.Name = "columns";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, this.columns.Count));
          foreach (ColumnOrSuperColumn _iter11 in this.columns)
          {
            _iter11.Write(oprot);
            oprot.WriteListEnd();
          }
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("KeySlice(");
      sb.Append("key: ");
      sb.Append(this.key);
      sb.Append(",columns: ");
      sb.Append(this.columns);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
