/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace Apache.Cassandra
{

  [Serializable]
  public partial class AuthenticationRequest : TBase
  {
    private Dictionary<string, string> _credentials;

    public Dictionary<string, string> Credentials
    {
      get
      {
        return _credentials;
      }
      set
      {
        __isset.credentials = true;
        this._credentials = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool credentials;
    }

    public AuthenticationRequest() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                Credentials = new Dictionary<string, string>();
                TMap _map24 = iprot.ReadMapBegin();
                for( int _i25 = 0; _i25 < _map24.Count; ++_i25)
                {
                  string _key26;
                  string _val27;
                  _key26 = iprot.ReadString();
                  _val27 = iprot.ReadString();
                  Credentials[_key26] = _val27;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("AuthenticationRequest");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Credentials != null && __isset.credentials) {
        field.Name = "credentials";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.String, TType.String, Credentials.Count));
          foreach (string _iter28 in Credentials.Keys)
          {
            oprot.WriteString(_iter28);
            oprot.WriteString(Credentials[_iter28]);
            oprot.WriteMapEnd();
          }
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("AuthenticationRequest(");
      sb.Append("Credentials: ");
      sb.Append(Credentials);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
