/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace FluentCassandra.Apache.Cassandra
{
  public static class cassandraConstants
  {
    public static string VERSION = "19.38.0";
  }
}
