/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Apache.Cassandra
{
  public enum Compression
  {
    GZIP = 1,
    NONE = 2,
  }
}
