/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

namespace Apache.Cassandra
{
  public enum Compression
  {
    GZIP = 1,
    NONE = 2,
  }
}
