/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace FluentCassandra.Apache.Cassandra
{
  public class Constants
  {
    public static string VERSION = "19.35.0";
  }
}
