/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

namespace Apache.Cassandra
{
  public enum CqlResultType
  {
    ROWS = 1,
    VOID = 2,
    INT = 3,
  }
}
