/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Apache.Cassandra
{
  public enum IndexOperator
  {
    EQ = 0,
    GTE = 1,
    GT = 2,
    LTE = 3,
    LT = 4,
  }
}
