/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace FluentCassandra.Apache.Cassandra
{
  public enum IndexType
  {
    KEYS = 0,
    CUSTOM = 1,
    COMPOSITES = 2,
  }
}
