/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace Apache.Cassandra
{

  [Serializable]
  public partial class TokenRange : TBase
  {
    private string _start_token;
    private string _end_token;
    private List<string> _endpoints;
    private List<string> _rpc_endpoints;
    private List<EndpointDetails> _endpoint_details;

    public string Start_token
    {
      get
      {
        return _start_token;
      }
      set
      {
        __isset.start_token = true;
        this._start_token = value;
      }
    }

    public string End_token
    {
      get
      {
        return _end_token;
      }
      set
      {
        __isset.end_token = true;
        this._end_token = value;
      }
    }

    public List<string> Endpoints
    {
      get
      {
        return _endpoints;
      }
      set
      {
        __isset.endpoints = true;
        this._endpoints = value;
      }
    }

    public List<string> Rpc_endpoints
    {
      get
      {
        return _rpc_endpoints;
      }
      set
      {
        __isset.rpc_endpoints = true;
        this._rpc_endpoints = value;
      }
    }

    public List<EndpointDetails> Endpoint_details
    {
      get
      {
        return _endpoint_details;
      }
      set
      {
        __isset.endpoint_details = true;
        this._endpoint_details = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool start_token;
      public bool end_token;
      public bool endpoints;
      public bool rpc_endpoints;
      public bool endpoint_details;
    }

    public TokenRange() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              Start_token = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              End_token = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.List) {
              {
                Endpoints = new List<string>();
                TList _list24 = iprot.ReadListBegin();
                for( int _i25 = 0; _i25 < _list24.Count; ++_i25)
                {
                  string _elem26 = null;
                  _elem26 = iprot.ReadString();
                  Endpoints.Add(_elem26);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.List) {
              {
                Rpc_endpoints = new List<string>();
                TList _list27 = iprot.ReadListBegin();
                for( int _i28 = 0; _i28 < _list27.Count; ++_i28)
                {
                  string _elem29 = null;
                  _elem29 = iprot.ReadString();
                  Rpc_endpoints.Add(_elem29);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.List) {
              {
                Endpoint_details = new List<EndpointDetails>();
                TList _list30 = iprot.ReadListBegin();
                for( int _i31 = 0; _i31 < _list30.Count; ++_i31)
                {
                  EndpointDetails _elem32 = new EndpointDetails();
                  _elem32 = new EndpointDetails();
                  _elem32.Read(iprot);
                  Endpoint_details.Add(_elem32);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("TokenRange");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Start_token != null && __isset.start_token) {
        field.Name = "start_token";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Start_token);
        oprot.WriteFieldEnd();
      }
      if (End_token != null && __isset.end_token) {
        field.Name = "end_token";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(End_token);
        oprot.WriteFieldEnd();
      }
      if (Endpoints != null && __isset.endpoints) {
        field.Name = "endpoints";
        field.Type = TType.List;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.String, Endpoints.Count));
          foreach (string _iter33 in Endpoints)
          {
            oprot.WriteString(_iter33);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (Rpc_endpoints != null && __isset.rpc_endpoints) {
        field.Name = "rpc_endpoints";
        field.Type = TType.List;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.String, Rpc_endpoints.Count));
          foreach (string _iter34 in Rpc_endpoints)
          {
            oprot.WriteString(_iter34);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (Endpoint_details != null && __isset.endpoint_details) {
        field.Name = "endpoint_details";
        field.Type = TType.List;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Endpoint_details.Count));
          foreach (EndpointDetails _iter35 in Endpoint_details)
          {
            _iter35.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("TokenRange(");
      sb.Append("Start_token: ");
      sb.Append(Start_token);
      sb.Append(",End_token: ");
      sb.Append(End_token);
      sb.Append(",Endpoints: ");
      sb.Append(Endpoints);
      sb.Append(",Rpc_endpoints: ");
      sb.Append(Rpc_endpoints);
      sb.Append(",Endpoint_details: ");
      sb.Append(Endpoint_details);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
